name: Pull Request - Autolabel
on:
  pull_request:
    types: [synchronize, ready_for_review, opened, edited]
    branches:
      - main
    
jobs:

  labeler:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v3.1
      with:
        configuration-path: .github/labeler.yaml
        sync-labels: 1
        repo-token: ${{ github.token }}