name: Pull Request - Validate title and description
on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main

env:
  PR_TITLE_FORMAT: ^CNS-[0-9]+:[[:space:]].+$

jobs:
  validate-pr-title:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-lastest
    container:
      image: bash:5.2
    steps:
      - run: |
          if ! [[ "${{ github.event.pull_request.title }}" =~ ${{ env.PR_TITLE_FORMAT }} ]]; then
              echo "::error title=${{ github.event.pull_request.title }}::PR title does not match regex formatting"
              exit 1
          fi

  validate-checklist:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-lastest
    steps:
    - name: Run actions/checkout 
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Issue / Pull request body regex validator
      uses: FabianKoestring/body-regex-validator-action@v0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_PATTERN: '^(.*What type of PR.*\[[xX]\].*Commit Message.*)$'
        PULL_REQUEST_COMMENT: 'This is my pr comment template.'
