name: Pull Request - Get timestamp
on:
  pull_request:
    types: [synchronize, ready_for_review, opened]
    branches:
      - main
    # *NOTE* MUST MATCH ./pull-request-ignore.yaml .on.pull_request.paths
    paths-ignore:
    - 'benchmarks/**'
    - 'docs/**'
    - 'README.md'
    - '.github/release.yaml'
    - '.github/workflows/ondemand-cleanup.yaml'
    - '.github/workflows/build.yaml'
    - '.github/workflows/kpp-e2e-pytest.yaml'
    - '.github/workflows/kpp-ephemeral-nightly-mgmt-cluster-test.yaml'
    - '.github/workflows/pull-request-ignore.yaml'
    - '.github/workflows/release-**'
    - '.github/workflows/sonobuoy**'
    - '.github/workflows/kpp-testing**'
    - 'scripts/requirements.txt'
    - 'scripts/wipe_account.py'
    - 'scripts/loop-add.sh'
    - 'scripts/app-cluster-tool.py'
    - 'scripts/.s3cfg'
    - 'bootstrap/Pulumi.*.yaml'
    - 'testing/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
  BRANCH: ${{ github.head_ref || github.ref_name }}
  B64_GITOPS_SSH_PRIVATE_KEY: ${{ secrets.B64_GITOPS_SSH_PRIVATE_KEY }}
  LINODE_API_TOKEN: ${{ secrets.DEV_LINODE_API_TOKEN }}
  LINODE_API_VERSION: v4beta
  PULUMI_CONFIG_PASSPHRASE: ""
  PULUMI_VERSION: "3.66.0"
  REGION: "us-ord"

jobs:
  current_ts:
    runs-on: ubuntu-lastest
    outputs:
      current_ts: ${{ steps.set_current_ts.outputs.current_ts }}
    steps:
      - id: set_current_ts
        run: echo "::set-output name=current_ts::gha$(date +%s)"
