name: Pull Request - Validate title and description
on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main

env:
  PR_TITLE_FORMAT: ^CNS-[0-9]+:[[:space:]].+$
  PR_TYPE_CHECK: \[\s*[xX]\s*\] [Breaking|New Feature|Bug Fix|Optimization|Refactor|Test|Documentation Update]

jobs:
  validate-pr-title:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    container:
      image: bash:5.2
    steps:
      - run: |
          if ! [[ "${{ github.event.pull_request.title }}" =~ ${{ env.PR_TITLE_FORMAT }} ]]; then
              echo "::error title=${{ github.event.pull_request.title }}::PR title does not match regex formatting"
              exit 1
          fi

  validate-checklist:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    container:
      image: bash:5.2
    steps:
      - run: |
          echo "${{ github.event.pull_request.body }}" | grep -q "${{ env.PR_TYPE_CHECK_REGEX }}"
          if [[ $? -ne 0 ]]; then
              echo "::error title=${{ github.event.pull_request.title }}::PR no type checked"
              exit 1
          fi
