name: Test updating a branch
on:
  workflow_dispatch:
    inputs:
      update_tst_cluster:
        type: boolean
        description: 'Update tst cluster (tst-cluster-env branch) to latest commit on main branch'
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  current_ts:
    runs-on: ubuntu-latest
    outputs:
      current_ts: ${{ steps.set_current_ts.outputs.current_ts }}
    steps:
      - id: set_current_ts
        run: echo "::set-output name=current_ts::gha$(date +%s)"

  run-e2e-tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      # checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          path: root

      # pretend to run a test
      - name: Run a test
        run: echo "Running a test"
         
  update-tst-cluster:
    needs: run-e2e-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          path: root

      - name: Output result of run-e2e-tests
        run: echo "Result = ${{ needs.run-e2e-tests.result }}"

      - name: Update 'tst-cluster-env' to latest commit on main branch
        if: ${{ needs.run-e2e-tests.result == 'success' }} && ${{ inputs.update_tst_cluster == 'true' }}
        working-directory: ./root
        run: |
          git checkout tst-cluster-env
          git pull origin main