name: Test updating a branch
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      update_tst_cluster:
        type: boolean
        description: 'Update tst cluster (tst-cluster-env branch) to latest commit on main branch'
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-e2e-tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      # checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          path: root

      # pretend to run a test
      - name: Run a test
        run: echo "Running a test"
         
  update-tst-cluster:
    # Should run on scheduled (nightly) tests that pass and manual dispatch (only if input is set to true)
    if: ${{ needs.run-e2e-tests.result == 'success' && !contains(inputs.update_tst_cluster, 'false') }}
    needs: run-e2e-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          path: root

      - name: Output result of run-e2e-tests
        run: echo "needs.run-e2e-tests.result = ${{ needs.run-e2e-tests.result }}"

      - name: Output update_tst_cluster input
        run: echo "inputs.update_tst_cluster = ${{ inputs.update_tst_cluster }}"

      - name: Update 'tst-cluster-env' to latest commit on main branch
        working-directory: ./root
        run: |
          git checkout tst-cluster-env
          git pull origin main
          git push origin tst-cluster-env
         
  deploy-tst-cluster:
    if: ${{ needs.run-e2e-tests.result == 'success' && !contains(inputs.update_tst_cluster, 'false') }}
    needs: [run-e2e-tests, update-tst-cluster]
    uses: srager13/gha-test/.github/workflows/deploy-cluster.yaml@main
    with:
      branch: tst-cluster-env
      command: up
      environment: ord-1-testing